### ISSUE TITLE
Win 7 Install failed

### ISSUE THREAD

**Issue by RJFSR** [blockchainfoundryinc/syscoin-spark-wallet#3]
Installed Spark on fully patched, up to date win 7 system. Multiple errors upon opening, multiple screen warnings, caught in an error loop, had to reboot to clear. Sorry, don't have screen shots.

**Comment by Keyare** [comment]
We would need more information to debug. Try joining our Discord channel so we can find the cause. Link is on syscoin.org, top right

**Comment by Keyare** [comment]
only 64 bit will be supported
